---
  - name: Install Java
    hosts: all
    roles:
      - java
  - name: Verify
    hosts: all
    gather_facts: false
    tasks:
    - name: Check Java can running
      command:
        cmd: "/opt/jdk/openjdk-11/bin/java -version"
      environment:
        PATH: "/opt/jdk/openjdk-11/bin:$PATH"
      changed_when: false
